Repository Sylius/PluginSkeleton, pull requests merged in 2019-01, with the labels that each got.

#154 Remove container cleanup in test environment (1.3)
  .travis.yml
  tests/Application/Kernel.php
Labels: Maintenance

#156 Update to Sylius 1.4-BETA
  .gitignore
  .travis.yml
  behat.yml.dist
  composer.json
  phpunit.xml.dist
  tests/Application/.env
  tests/Application/.env.prod.dist
  tests/Application/.env.test
  tests/Application/.env.test.dist
  tests/Application/.gitignore
  tests/Application/bin/console
  tests/Application/config/bootstrap.php
  tests/Application/config/bundles.php
  tests/Application/config/services_test.yaml
  tests/Application/public/index.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/suites.yml
Labels: Maintenance

#157 Add support for PHP 7.3 & remove fake Symfony builds
  .travis.yml
Labels: Maintenance

#158 Upgrade guide from v1.3.x to v1.4.0
  UPGRADE-1.4.md
Labels: Documentation, Maintenance

#159 Upgrade guide from v1.2.x to v1.4.0
  UPGRADE-1.4.md
Labels: Documentation, Maintenance

#139 Mention database credentials setup in README
  README.md
Labels: Documentation
