Repository Sylius/PluginSkeleton, pull requests merged in 2025-07, with the labels that each got.

#459 Add base configuration for entities in Test Application + configuration and dependencies improvements
  composer.json
  tests/TestApplication/.env
  tests/TestApplication/.env.test
  tests/TestApplication/config/config.yaml
  tests/TestApplication/src/Entity/.gitkeep
Labels: DX, Maintenance

#462 [Behat] Add Panther config
  behat.yml.dist
Labels: Maintenance

#465 Remove unneeded Twig Hooks config
  config/app/twig_hooks/admin.yaml
  config/app/twig_hooks/shop.yaml
  config/config.yaml
  config/twig_hooks/shop.yaml
Labels: DX, Maintenance

#467 Bump sylius/test-application + minor routes refactor
  .gitignore
  config/routes/admin.yaml
  config/routes/shop.yaml
  tests/TestApplication/.env
  tests/TestApplication/config/routes.yaml
Labels: DX, Maintenance, Dependencies

#469 [Composer] Remove symfony/flex to ease installation without unneeded recipes
  .github/workflows/build.yml
  composer.json
Labels: DX, Dependencies

#470 [CI] Run builds on different Sylius versions
  .github/workflows/build.yaml
Labels: Maintenance

#464 Update README.md
  README.md
Labels: Maintenance

#471 [Composer] Remove unneeded dependency to symfony/contracts + minor clean up in ECS config file
  composer.json
  ecs.php
Labels: Maintenance, Dependencies

#472 [AI] Introduce guides to ease cleaning, renaming and providing support for different versions of Sylius
  AGENTS.md
  CLAUDE.md
  CLEANUP_GUIDE.md
  COMPATIBILITY_GUIDE.md
  RENAME_GUIDE.md
Labels: DX
